# Generated by Django 3.1.6 on 2021-03-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='role',
            field=models.SmallIntegerField(choices=[(1, 'super admin'), (2, 'guest')], default=2),
        ),
    ]
