# Generated by Django 3.1.6 on 2021-03-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('created_at', models.DateField(verbose_name='Дата публикации')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Описание')),
                ('num_pages', models.IntegerField(default=0, verbose_name='Количество страниц')),
                ('genre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Книга-Журнал',
                'verbose_name_plural': 'Книги-Журналы',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('created_at', models.DateField(verbose_name='Дата публикации')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Описание')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Типы')),
                ('publisher', models.CharField(blank=True, max_length=255, null=True, verbose_name='Издатель')),
            ],
            options={
                'verbose_name': 'Книга-Журнал',
                'verbose_name_plural': 'Книги-Журналы',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
