# Generated by Django 3.1.6 on 2021-03-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_journal_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='role',
        ),
        migrations.AlterField(
            model_name='journal',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'BULLET'), (2, 'FOOD'), (3, 'TRAVEL'), (4, 'SPORT')], default=1, verbose_name='Типы'),
        ),
    ]
