USER_ROLE_SUPER_USER = 1
USER_ROLE_GUEST = 2
USER_ROLES = (
    (USER_ROLE_SUPER_USER, 'super admin'),
    (USER_ROLE_GUEST, 'guest'),
)

TYPE_BULLET = 'BULLET'
TYPE_FOOD = 'FOOD'
TYPE_TRAVEL = 'TRAVEL'
TYPE_SPORT = 'SPORT'
TYPE = (
    (TYPE_BULLET, 'BULLET'),
    (TYPE_FOOD, 'FOOD'),
    (TYPE_TRAVEL, 'TRAVEL'),
    (TYPE_SPORT, 'SPORT')

)
